language: python
dist: xenial
sudo: required
services:
  - redis
env:
  global:
    - REDIS_ADDR=localhost
    # REDIS_PASS
    - secure: fNM66kLGLUnuippsLYe9TRAc2hFOlE6ThlkJmIkTq1a+P83PpjVyZYK1ujmuMrPeEI4R/+Tn1ueUjqWXSyswr4DSUuwL6fdyVFh/wh4B+ZgUBXlEAPqN6haLilmcqlFHHQ4+ZsScxHVyBzTzLfnGSC2X6HZaZAHrdeb5GtC3C9IR1TwoHsJrjQq1fC07G0Jej4upHfz520q3HWcV03+fC5GfAbeb/kCCu9GIAMS9INh69EPnKZH0T7CYvAHoMZeWX3Awp+LKgpXieZ77Jj8yN71rNMJKfSOc7CUAZYZpw6ZQZDLA7WbrFOQqXqiH6UkxRHMzk/2pv/lycKNsYktEdd+uH2tStmAM3c8KsGDDIz9+YJmKHkfZy5XJZiaFqdWxs6VCsLv4xu8QdoUUqmne28ZLEgoroxHdy0XjemF9hOrKuaxKyfyQL6FJslBMpWwBX+UA2wrQNUt1PKEfISs+3OC3xWyEZ63oMF9Bd/azvnOc9MK+xme6bFZZszWtKJFWV4Kx8OMrRzD2zeyCwKBMROQ9vpvoxF1mtaDHmkJ9rX22DE2/KZ4YTaQ2wBbRWGSKepJVI4VxYLWi67/Rfad0eaC5Eh4Dsk/oJ4vJv7J7KQV9LmiUBqStNQTdq8O+ZQWM6EMd/Rey9x+4C+jiGz98dfJbLgMNIL86jhQR6r9echg=
python: 
  - "3.5"
  - "3.7"
before_script:
  - ruby -e 'require "erb"; redis_pass=ENV["REDIS_PASS"]; File.write("config/redis.conf",ERB.new(File.read("config/redis.conf.erb")).result(binding))'
  - sudo cp config/redis.conf /etc/redis/redis.conf && sudo systemctl restart redis-server.service
script:
  - python3 test_counter.py
